customized: false
imported_at: '2026-07-03T02:10:07.325679+00:00'
imported_by: dkhai
library_version: '1.0'
notes: ''
original_hash: sha256:5ec5308c5231823b3e99bff096b523698d3088ecea1e027d3e4d0fcb13f48f07
source_path: skills/configure-ecc/SKILL.md
source_project: everything-claude-code
