customized: false
imported_at: '2026-03-31T02:45:55.838147+00:00'
imported_by: dkhai
library_version: '1.0'
notes: ''
original_hash: sha256:b2d18f90ea5f5b7e6c357c3ded7353fa2d23b04464eed4b81745b0c8340e31ba
source_path: skills/deployment-patterns/SKILL.md
source_project: everything-claude-code
