customized: false
imported_at: '2026-07-03T02:10:07.342488+00:00'
imported_by: dkhai
library_version: '1.0'
notes: ''
original_hash: sha256:718928a11187996eb8438fb1c5de64edcf9d7a002316fbfee385f01fad121224
source_path: skills/django-security/SKILL.md
source_project: everything-claude-code
