customized: false
imported_at: '2026-07-03T02:10:07.411955+00:00'
imported_by: dkhai
library_version: '1.0'
notes: ''
original_hash: sha256:94f7c7eab50125d8af5e148bc3776dfc904b4baa95f32218d2293296e923ba5c
source_path: skills/perl-security/SKILL.md
source_project: everything-claude-code
