customized: false
imported_at: '2026-07-03T02:10:07.423886+00:00'
imported_by: dkhai
library_version: '1.0'
notes: ''
original_hash: sha256:2f031a50bf3ff9279df08529e6e933b30f850e7e294f3acf37b9221ee95025da
source_path: skills/quarkus-security/SKILL.md
source_project: everything-claude-code
